mainapp/urls.py
from django.contrib import admin
from django.urls import path, include
# machine learning calls
# from prediction.urls import urlpatterns as endpoints_urlpatterns

# static files config
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import url


from web import views
urlpatterns = [
    # APIs
    path('login', views.Index.as_view(), name="index"),
    path('admin/', admin.site.urls),
    # path('api/auth/', include('users.urls')),
    # path('api/', include('prediction.urls')),


    # Templates
    path('', views.Index.as_view(), name='index'),
    path('users/', include('users.urls')),
    path('web/', include('web.urls')),
    path('sacco/', include('sacco.urls')),

    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    
]
# urlpatterns += endpoints_urlpatterns
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path, include
from web import views
from django.conf.urls import url
app_name = 'web'

urlpatterns = [
	path('home', views.Index.as_view(), name="home"),
	path('apply', views.Apply.as_view(), name="apply"),
	path('alumni', views.Alumni.as_view(), name="alumni"),
	path('contacts', views.Contacts.as_view(), name="contacts"),
	path('help', views.Help.as_view(), name="help"),
	path('sign_in', views.SignIn.as_view(), name="sign_in"),
	path('sign_up', views.SignUp.as_view(), name="sign_up"),
	path('research', views.Research.as_view(), name="research"),
	path('communites', views.Communites.as_view(), name="communites"),
	path('events', views.Events.as_view(), name="events"),
	path('our_staff', views.FacultyStaff.as_view(), name="our_staff"),
	path('future_members', views.FutureStudents.as_view(), name="future_members"),
	path('current_members', views.CurrentStudents.as_view(), name="current_members"),
	path('courses', views.Courses.as_view(), name="courses"),
    path('comment_post/<int:pk>/', views.comment_post, name='comment_post'),
    path('research_detail/<int:pk>/', views.ResearchDetailView.as_view(), name='research_detail'),

]

web/templates/web/pages/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Title -->
    <title>BOSCCA</title>

    <!-- Required Meta Tags Always Come First -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'theme_favicon.ico' %}">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Barlow:300,400,400i,500,700%7CAlegreya:400" rel="stylesheet">

    <!-- CSS theme Compulsory -->
    <link rel="stylesheet" href="{% static 'theme_assets/vendor/bootstrap/bootstrap.min.css' %}">

    <!-- CSS Implementing Plugins -->
    <link rel="stylesheet" href="{% static 'theme_assets/vendor/icon-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'theme_assets/vendor/icon-line-pro/style.css' %}">
    <link rel="stylesheet" href="{% static 'theme_assets/vendor/icon-hs/style.css' %}">
    <link rel="stylesheet" href="{% static 'theme_assets/vendor/icon-material/material-icons.css' %}">
    <link rel="stylesheet" href="{% static 'theme_assets/vendor/animate.css' %}">
    <link rel="stylesheet" href="{% static 'theme_assets/vendor/hs-megamenu/src/hs.megamenu.css' %}">
    <link rel="stylesheet" href="{% static 'theme_assets/vendor/hamburgers/hamburgers.min.css' %}">
    <link rel="stylesheet" href="{% static 'theme_assets/vendor/slick-carousel/slick/slick.css' %}">
    <link rel="stylesheet" href="{% static 'theme_assets/vendor/fancybox/jquery.fancybox.css' %}">
    <link rel="stylesheet" href="{% static 'theme_assets/vendor/chosen/chosen.css' %}">
    <link rel="stylesheet" href="{% static 'theme_assets/vendor/dzsparallaxer/dzsparallaxer.css' %}">
    <link rel="stylesheet" href="{% static 'theme_assets/vendor/dzsparallaxer/dzsscroller/scroller.css' %}">
    <link rel="stylesheet" href="{% static 'theme_assets/vendor/dzsparallaxer/advancedscroller/plugin.css' %}">
    <link rel="stylesheet" href="{% static 'theme_assets/vendor/hs-bg-video/hs-bg-video.css' %}">
  <link rel="stylesheet" href="{% static 'theme_assets/vendor/jquery-ui/themes/base/jquery-ui.min.css' %}">
  <link rel="stylesheet" href="{% static 'theme_assets/vendor/hs-bg-video/hs-bg-video.css' %}">
   
    <!-- CSS SACCO Theme -->
    <link rel="stylesheet" href="{% static 'app_assets/css/styles.multipage-education.css' %}">

    <!-- CSS Customization -->
    <link rel="stylesheet" href="{% static 'theme_assets/css/custom.css' %}">
  </head>

  <body>
    <main>
      {% include 'web/pages/base/header.html'%}
        {% block content %} {% endblock %}

    </main>
    
  
    <!-- JS theme Compulsory -->
    <script src="{% static 'theme_assets/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'theme_assets/vendor/jquery-migrate/jquery-migrate.min.js' %}"></script>
    <script src="{% static 'theme_assets/vendor/popper.js/popper.min.js' %}"></script>
    <script src="{% static 'theme_assets/vendor/bootstrap/bootstrap.min.js' %}"></script>

    <!-- JS Implementing Plugins -->
    <script src="{% static 'theme_assets/vendor/hs-megamenu/src/hs.megamenu.js' %}"></script>
    <script src="{% static 'theme_assets/vendor/slick-carousel/slick/slick.js' %}"></script>
    <script src="{% static 'theme_assets/vendor/fancybox/jquery.fancybox.min.js' %}"></script>
    <script src="{% static 'theme_assets/vendor/chosen/chosen.jquery.js' %}"></script>
    <script src="{% static 'theme_assets/vendor/hs-bg-video/hs-bg-video.js' %}"></script>
    <script src="{% static 'theme_assets/vendor/hs-bg-video/vendor/player.min.js' %}"></script>

    <script src="{% static 'theme_assets/vendor/dzsparallaxer/dzsparallaxer.js' %}"></script>
    <script src="{% static 'theme_assets/vendor/dzsparallaxer/dzsscroller/scroller.js' %}"></script>
    <script src="{% static 'theme_assets/vendor/dzsparallaxer/advancedscroller/plugin.js' %}"></script>
    <script src="{% static 'theme_assets/vendor/hs-bg-video/hs-bg-video.js' %}"></script>
    <script src="{% static 'theme_assets/vendor/hs-bg-video/vendor/player.min.js' %}"></script>

    <!-- JS SACCO -->
    <script src="{% static 'theme_assets/js/hs.core.js' %}"></script>
    <script src="{% static 'theme_assets/js/components/hs.header.js' %}"></script>
    <script src="{% static 'theme_assets/js/helpers/hs.hamburgers.js' %}"></script>
    <script src="{% static 'theme_assets/js/components/hs.dropdown.js' %}"></script>
    <script src="{% static 'theme_assets/js/helpers/hs.height-calc.js' %}"></script>
    <script src="{% static 'theme_assets/js/components/hs.carousel.js' %}"></script>
    <script src="{% static 'theme_assets/js/components/hs.sticky-block.js' %}"></script>
    <script src="{% static 'theme_assets/js/components/hs.popup.js' %}"></script>
    <script src="{% static 'theme_assets/js/components/hs.go-to.js' %}"></script>

    <!-- JS Customization -->
    <script src="{% static 'theme_assets/js/custom.js' %}"></script>

    <!-- JS Plugins Init. -->
    <script>
      $(document).on('ready', function () {
        // initialization of header
        $.HSCore.components.HSHeader.init($('#js-header'));
        $.HSCore.helpers.HSHamburgers.init('.hamburger');

        // initialization of HSMegaMenu component
        $('.js-mega-menu').HSMegaMenu({
          event: 'hover',
          pageContainer: $('.container'),
          breakpoint: 991
        });

        // initialization of HSDropdown component
        $.HSCore.components.HSDropdown.init($('[data-dropdown-target]'), {
          afterOpen: function () {
            $(this).find('input[type="search"]').focus();
          }
        });

        // initialization of carousel
        $.HSCore.components.HSCarousel.init('[class*="js-carousel"]');

        // initialization of video on background
        $.HSCore.helpers.HSBgVideo.init('.js-bg-video');
        // initialization of header's height equal offset
        $.HSCore.helpers.HSHeightCalc.init();

        // initialization of popups
        $.HSCore.components.HSPopup.init('.js-fancybox');
      // initialization of forms
      $.HSCore.components.HSDatepicker.init('#datepickerInline');
            // initialization of custom select
      $.HSCore.components.HSSelect.init('.js-custom-select');

        // initialization of go to
        $.HSCore.components.HSGoTo.init('.js-go-to');
      });
      $(window).on('load', function () {
        // initialization of HSScrollNav
        $.HSCore.components.HSScrollNav.init($('#js-scroll-nav'), {
          duration: 700,
          over: $('.u-secondary-navigation')
        });

        // initialization of sticky blocks
        $.HSCore.components.HSStickyBlock.init('.js-sticky-block');
      });



      $(window).on('resize', function () {
        setTimeout(function () {
          $.HSCore.components.HSTabs.init('[role="tablist"]');
        }, 200);
      });

              // Signin Tab
        $('#signin-link, #go-back-link').on('click', function(e) {
          e.preventDefault();
          $('#signin, #go-back-link').show();
          $('#signup').hide();
          $('#forgot-password').hide();
        });

        $('#signup-link').on('click', function(e) {
          e.preventDefault();
          $('#signup').show();
          $('#signin, #go-back-link').hide();
          $('#forgot-password').hide();
        });

        $('#forgot-password-link').on('click', function(e) {
          e.preventDefault();
          $('#forgot-password').show();
          $('#signin').hide();
          $('#signup').hide();
        });
    </script>
  </body>
</html>

web/templates/web/pages/base/header.html
     {% load static %}
     <!-- Header -->
      <header id="js-header" class="u-header">
        <div class="u-header__section">
          <!-- Topbar -->
          <div class="g-bg-main">
            <div class="container g-py-5">
              <ul class="list-inline d-flex align-items-center g-mb-0">
                <li class="list-inline-item d-none d-lg-inline-block">
                  <a class="u-link-v5 g-brd-around g-brd-white-opacity-0_2 g-color-white-opacity-0_7 g-color-white--hover g-font-size-12 g-rounded-20 text-uppercase g-px-20 g-py-10" href="{% url 'web:apply' %}">Join our Classes</a>
                </li>

                <!-- Jump To -->
                <li class="list-inline-item g-pos-rel">
                  <a id="jump-to-dropdown-invoker" class="d-block d-lg-none u-link-v5 g-color-white-opacity-0_7 g-color-white--hover g-font-size-12 text-uppercase g-py-7" href="#"
                     aria-controls="jump-to-dropdown"
                     aria-haspopup="true"
                     aria-expanded="false"
                     data-dropdown-event="hover"
                     data-dropdown-target="#jump-to-dropdown"
                     data-dropdown-type="css-animation"
                     data-dropdown-duration="0"
                     data-dropdown-hide-on-scroll="true"
                     data-dropdown-animation-in="fadeIn"
                     data-dropdown-animation-out="fadeOut">
                    Jump To
                    <i class="g-ml-3 fa fa-angle-down"></i>
                  </a>
                  <ul id="jump-to-dropdown" class="list-unstyled ushadow-v39 g-brd-around g-brd-4 g-brd-white g-bg-secondary g-pos-abs g-left-0 g-z-index-99 g-mt-13"
                      aria-labelledby="jump-to-dropdown-invoker">
                    <li class="dropdown-item g-brd-bottom g-brd-2 g-brd-white g-px-0 g-py-2">
                      <a class="nav-link g-color-main g-color-primary--hover g-bg-secondary-dark-v2--hover g-font-size-default" href="{% url 'web:apply' %}">Register Now</a>
                    </li>
                    <li class="dropdown-item g-brd-bottom g-brd-2 g-brd-white g-px-0 g-py-2">
                      <a class="nav-link g-color-main g-color-primary--hover g-bg-secondary-dark-v2--hover g-font-size-default" href="{% url 'web:communites' %}">Credit Union Communities</a>
                    </li>
                    <li class="dropdown-item g-brd-bottom g-brd-2 g-brd-white g-px-0 g-py-2">
                      <a class="nav-link g-color-main g-color-primary--hover g-bg-secondary-dark-v2--hover g-font-size-default" href="{% url 'web:research' %}">Credit Unions  Research</a>
                    </li>
                    <li class="dropdown-item g-brd-bottom g-brd-2 g-brd-white g-px-0 g-py-2">
                      <a class="nav-link g-color-main g-color-primary--hover g-bg-secondary-dark-v2--hover g-font-size-default" href="{% url 'web:help' %}">Help</a>
                    </li>
                    <li class="dropdown-item g-brd-bottom g-brd-2 g-brd-white g-px-0 g-py-2">
                      <a class="nav-link g-color-main g-color-primary--hover g-bg-secondary-dark-v2--hover g-font-size-default" href="{% url 'web:contacts' %}">Contacts us</a>
                    </li>
                    <li class="dropdown-item g-px-0 g-py-2">
                      <a class="nav-link g-color-white g-bg-primary g-bg-primary-light-v1--hover g-font-size-default" href="{% url 'web:sign_in' %}">Sign in</a>
                    </li>
                  </ul>
                </li>
                <!-- End Jump To -->

                <!-- Links -->
                <li class="list-inline-item d-none d-lg-inline-block">
                  <a class="u-link-v5 g-color-white-opacity-0_7 g-color-white--hover g-font-size-12 text-uppercase g-px-10 g-py-15" href="{% url 'web:communites' %}">Credit Union Communities</a>
                </li>
          
                <li class="list-inline-item d-none d-lg-inline-block">
                  <a class="u-link-v5 g-color-white-opacity-0_7 g-color-white--hover g-font-size-12 text-uppercase g-px-10 g-py-15" href="{% url 'web:help' %}">Help</a>
                </li>
                <li class="list-inline-item d-none d-lg-inline-block">
                  <a class="u-link-v5 g-color-white-opacity-0_7 g-color-white--hover g-font-size-12 text-uppercase g-px-10 g-py-15" href="{% url 'web:contacts' %}">Contacts</a>
                </li>
                <li class="list-inline-item d-none d-lg-inline-block">
                  <a class="u-link-v5 u-shadow-v19 g-color-white--hover g-bg-white g-bg-primary--hover g-font-size-12 text-uppercase g-rounded-20 g-px-18 g-py-8 g-ml-10" href="{% url 'web:sign_in' %}">Sign in</a>
                </li>
                <!-- End Links -->

                <!-- Search -->
                <li class="list-inline-item g-ml-15--lg ml-auto">
                  <form id="searchform-1" class="input-group u-shadow-v19 g-brd-primary--focus g-rounded-20">
                    <input class="form-control g-brd-none g-bg-white g-font-size-12 text-uppercase g-rounded-left-20 g-pl-20 g-py-9" type="text" placeholder="Search here ...">
                    <button class="btn input-group-addon d-flex align-items-center g-brd-none g-color-white g-bg-primary g-bg-primary-light-v1--hover g-font-size-13 g-rounded-right-20 g-transition-0_2" type="button">
                      <i class="fa fa-search"></i>
                    </button>
                  </form>
                </li>
                <!-- End Search -->
              </ul>
            </div>
          </div>
          <!-- End Topbar -->

          <div class="container">
            <!-- Nav -->
            <nav class="js-mega-menu navbar navbar-expand-lg g-px-0 g-py-5 g-py-0--lg">
              <!-- Logo -->
              <a class="navbar-brand g-max-width-170 g-max-width-200--lg" href="{% url 'web:home' %}">
                <img class="img-fluid g-hidden-lg-down g-width-80" src="{% static 'app_assets/img/logo/bost.png' %}" alt="Logo">
                <img class="img-fluid g-width-80 g-hidden-md-down g-hidden-xl-up" src="{% static 'app_assets/img/logo/logo-mini.png' %}" alt="Logo">
                <img  class="img-fluid g-hidden-lg-up" src="{% static 'app_assets/img/logo/bost.png' %}" alt="Logo">
              </a>
              <!-- End Logo -->

              <!-- Responsive Toggle Button -->
              <button class="navbar-toggler navbar-toggler-right btn g-line-height-1 g-brd-none g-pa-0" type="button"
                      aria-label="Toggle navigation"
                      aria-expanded="false"
                      aria-controls="navBar"
                      data-toggle="collapse"
                      data-target="#navBar">
                <span class="hamburger hamburger--slider g-px-0">
                  <span class="hamburger-box">
                    <span class="hamburger-inner"></span>
                  </span>
                </span>
              </button>
              <!-- End Responsive Toggle Button -->

{% include 'web/pages/base/nav.html' %}
          </div>
        </div>
      </header>
      <!-- End Header -->

web/templates/web/pages/base/nav.html
{% load static %}
		
		<!-- Navigation -->
							<div id="navBar" class="collapse navbar-collapse">
								<ul class="navbar-nav align-items-lg-center g-py-30 g-py-0--lg ml-auto">
									<!-- Pages - Mega Menu -->
									<li class="nav-item hs-has-mega-menu"
											data-animation-in="fadeIn"
											data-animation-out="fadeOut"
											data-position="left">
										<!-- <a id="mega-menu-label-1" class="nav-link g-color-primary--hover g-font-size-15 g-font-size-17--xl g-px-15--lg g-py-10 g-py-30--lg" href="#!"
											 aria-haspopup="true"
											 aria-expanded="false">
											National SACCO Boards
											<i class="hs-icon hs-icon-arrow-bottom g-font-size-11 g-ml-7"></i>
										</a>  -->

										 <!-- Mega Menu -->
										<div class="w-100 hs-mega-menu u-shadow-v39 g-brd-around g-brd-7 g-brd-white g-bg-secondary g-text-transform-none g-pa-30 g-pa-50--lg g-my-20 g-my-0--lg" aria-labelledby="mega-menu-label-1">
											<span class="d-block h1 g-brd-bottom g-brd-2 g-brd-main pb-2 mb-5">SACCOs IN AFRICA</span>

											<div class="row">
												<div class="col-sm-6 col-lg-3">
													<!-- Links -->
													<ul class="list-unstyled g-pr-30 mb-0">
														<li class="py-2">

															<a class="d-flex g-color-main g-color-primary--hover g-text-underline--none--hover g-py-5" href="{% url 'web:courses' %}">
															 <img class="img-fluid g-hidden-lg-down g-width-20" src="{% static 'app_assets/img/logo/bost.png' %}" alt="Logo">
                <img class="img-fluid g-width-20 g-hidden-md-down g-hidden-xl-up" src="{% static 'app_assets/img/logo/logo-mini.png' %}" alt="Logo">
                <img  class="img-fluid g-hidden-lg-up" src="{% static 'app_assets/img/logo/bost.png' %}" alt="Logo">
            	 <span style="margin-left:3%;">NASACCOS</span>
																<i class="g-color-primary g-font-size-15 g-pos-rel g-top-5 ml-auto material-icons">arrow_forward</i>
															</a>
														</li>
			
													</ul>
													<!-- End Links -->
												</div>
											</div>
										</div>
										<!-- End Mega Menu -->
									</li>
									<!-- End Pages - Mega Menu -->
									<li class="nav-item">
										<a class="nav-link g-color-primary--hover g-font-size-15 g-font-size-17--xl g-px-15--lg g-py-10 g-py-30--lg" href="{% url 'web:home' %}">
											Home
										</a>
									</li>

									<li class="nav-item">
										<a class="nav-link g-color-primary--hover g-font-size-15 g-font-size-17--xl g-px-15--lg g-py-10 g-py-30--lg" href="{% url 'web:communites' %}">
											About Us
										</a>
									</li>
									<li class="nav-item">
										<a class="nav-link g-color-primary--hover g-font-size-15 g-font-size-17--xl g-px-15--lg g-py-10 g-py-30--lg" href="{% url 'web:future_members' %}">
											Join us
										</a>
									</li>
									<li class="nav-item">
										<a class="nav-link g-color-primary--hover g-font-size-15 g-font-size-17--xl g-px-15--lg g-py-10 g-py-30--lg" href="{% url 'web:current_members' %}">
											Our Members
										</a>
									</li>
									<li class="nav-item">
										<a class="nav-link g-color-primary--hover g-font-size-15 g-font-size-17--xl g-px-15--lg g-py-10 g-py-30--lg" href="{% url 'web:our_staff' %}">
											Board Members
										</a>
									</li>
									<li class="nav-item">
										<a class="nav-link g-color-primary--hover g-font-size-15 g-font-size-17--xl g-px-15--lg g-py-10 g-py-30--lg" href="{% url 'web:research' %}">
											Blog
										</a>
									</li>
									<!-- <li class="nav-item">
										<a class="nav-link g-color-primary--hover g-font-size-15 g-font-size-17--xl g-px-15--lg g-py-10 g-py-30--lg" href="{% url 'web:events' %}">
											SACCOs Events
										</a>
									</li> -->
									<!-- <li class="nav-item">
										<a class="nav-link g-color-primary--hover g-font-size-15 g-font-size-17--xl g-pl-15--lg g-pr-0--lg g-py-10 g-py-30--lg" href="{% url 'web:alumni' %}">
											Alumni
										</a>
									</li> -->
								</ul>
							</div>
							<!-- End Navigation -->
						</nav>
						<!-- End Nav -->