mainapp/urls.py
from django.contrib import admin
from django.urls import path, include
# machine learning calls
# from prediction.urls import urlpatterns as endpoints_urlpatterns

# static files config
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import url


from web import views
urlpatterns = [
    # APIs
    path('login', views.Index.as_view(), name="index"),
    path('admin/', admin.site.urls),
    # path('api/auth/', include('users.urls')),
    # path('api/', include('prediction.urls')),


    # Templates
    path('', views.Index.as_view(), name='index'),
    path('users/', include('users.urls')),
    path('web/', include('web.urls')),
    path('sacco/', include('sacco.urls')),

    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    
]
# urlpatterns += endpoints_urlpatterns
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from users.views import *
from django.conf.urls import url
app_name = 'users'
urlpatterns = [
   path('index/', index, name='index'),
   path('logout/', logout, name='logout'),
   path('add_tutor/', add_tutor, name='add_tutor'),
   path('add_new_member/', add_new_member, name='add_new_member'),
   path('add_sacco/', add_sacco, name='add_sacco'),
   path('add_city/', add_city, name='add_city'),
   path('get_citites/', get_citites, name='get_citites'),
   path('get_countries/', get_countries, name='get_countries'),
   path('assign_member/', assign_member, name='assign_member'),
   path('view_members/', view_members, name='view_members'),
   path('view_tutors/', view_tutors, name='view_tutors'),
   path('assign_tutor/', assign_tutor, name='assign_tutor'),
   path('view_executives/', view_executives, name='view_executives'),
   path('sign_up/',sign_up,name='sign_up'),
   path('sign_in/', sign_in, name='sign_in'),
#    path('profile/$', profile, name='profile'),
    # path('login/', APILoginView.as_view(), name='api_login')
   url(
        r"^profile/(?P<profile_id>.)", profile, name="profile"
    ),
]

web/urls.py
from django.urls import path, include
from web import views
from django.conf.urls import url
app_name = 'web'

urlpatterns = [
	path('home', views.Index.as_view(), name="home"),
	path('apply', views.Apply.as_view(), name="apply"),
	path('alumni', views.Alumni.as_view(), name="alumni"),
	path('contacts', views.Contacts.as_view(), name="contacts"),
	path('help', views.Help.as_view(), name="help"),
	path('sign_in', views.SignIn.as_view(), name="sign_in"),
	path('sign_up', views.SignUp.as_view(), name="sign_up"),
	path('research', views.Research.as_view(), name="research"),
	path('communites', views.Communites.as_view(), name="communites"),
	path('events', views.Events.as_view(), name="events"),
	path('our_staff', views.FacultyStaff.as_view(), name="our_staff"),
	path('future_members', views.FutureStudents.as_view(), name="future_members"),
	path('current_members', views.CurrentStudents.as_view(), name="current_members"),
	path('courses', views.Courses.as_view(), name="courses"),
    path('comment_post/<int:pk>/', views.comment_post, name='comment_post'),
    path('research_detail/<int:pk>/', views.ResearchDetailView.as_view(), name='research_detail'),

]

education/models.py
from django.db import models
from users.models import *
from sacco.models import *

# Create your models here.

class EducationDepartment(models.Model):
	sacco =  models.ForeignKey(SACCO, on_delete=models.CASCADE ,default=None)
	name = models.CharField(null=True ,blank=True,max_length=20)
	mission =models.TextField(null=True ,blank=True)
	vision =models.TextField(null=True ,blank=True)
	statement =models.TextField(null=True ,blank=True)
	image = models.ImageField(upload_to="media/%Y/%m/%d",null=True, blank=True)
	video = models.FileField(upload_to="media/%Y/%m/%d",null=True, blank=True)
	def __str__(self):
		return self.name

class Tutor(models.Model):
	tutor_id = models.CharField(max_length=100, null=True, blank=True,db_index=True)
	profile = models.ForeignKey(SaccoStaffMember, related_name="tutor", verbose_name="Tutor Account", on_delete = models.CASCADE,null=True, blank=True,default=None)
	sacco = models.ForeignKey(SACCO, on_delete = models.CASCADE,null=True, blank=True,default=None)
	education_department =  models.ForeignKey(EducationDepartment, on_delete=models.CASCADE,null=True ,blank=True,default=None)
	signup_date = models.DateTimeField(auto_now=True)
	def __str__(self):
		return self.profile.user.first_name


class Student(models.Model):
	student_id = models.CharField(max_length=100, null=True, blank=True,db_index=True)
	profile = models.ForeignKey(AccountUser, related_name="student_profile", on_delete = models.CASCADE,null=True, blank=True,default=None)
	sacco = models.ForeignKey(SACCO, on_delete = models.CASCADE,null=True, blank=True,default=None)
	education_department =  models.ForeignKey(EducationDepartment, on_delete=models.CASCADE,null=True ,blank=True,default=None)
	registration_date = models.DateTimeField(auto_now=True)
	def __str__(self):
		return self.profile.user.first_name

class Course(models.Model):
	instructor = models.ForeignKey(EducationDepartment, related_name="education_department",default=None, verbose_name="Education Department", on_delete = models.CASCADE,null=True, blank=True)
	course_id = models.CharField(max_length=100, null=True, blank=True,db_index=True)
	course_name = models.CharField(max_length=100, null=True, blank=True,db_index=True)
	lead_tutor = models.ForeignKey(Tutor, related_name="lead_tutor", verbose_name="Tutor", on_delete = models.CASCADE,null=True, blank=True,default=None)
	education_department =  models.ForeignKey(EducationDepartment, on_delete=models.CASCADE,null=True ,blank=True)
	course_length = models.CharField(max_length=100, null=True, blank=True,db_index=True)
	
	def __str__(self):
		return self.course_name


class Class(models.Model):
	class_id = models.CharField(max_length=100, null=True, blank=True,db_index=True)
	instructor = models.ForeignKey(Tutor, related_name="class_instructor", verbose_name="Class Instructor", on_delete = models.CASCADE,null=True, blank=True,default=None)
	course = models.ForeignKey(Course, related_name="class_course", verbose_name="Course", on_delete = models.CASCADE,null=True, blank=True,default=None)
	students = models.ManyToManyField(Student)
	def __str__(self):
		return self.course.course_name

class Survey(models.Model):
	survey_id = models.CharField(max_length=100, null=True, blank=True,db_index=True)
	survey_name = models.CharField(max_length=100, null=True, blank=True,db_index=True)

	def __str__(self):
		return self.survey_name

class SurveyItem(models.Model):
	survey = models.ForeignKey(Survey, related_name="survey", verbose_name="Survey", on_delete = models.CASCADE,null=True, blank=True,default=None)
	question =models.TextField(null=True ,blank=True)
	answer =models.TextField(null=True ,blank=True)

	def __str__(self):
		return self.survey.survey_name


class Module(models.Model):
	module_id = models.CharField(max_length=100, null=True, blank=True,db_index=True)
	module_name = models.CharField(max_length=100, null=True, blank=True,db_index=True)
	course = models.ForeignKey(Course, related_name="course", verbose_name="Course", on_delete = models.CASCADE,null=True, blank=True,default=None)
	tutor = models.ForeignKey(Tutor, related_name="module_tutor", verbose_name="Tutor", on_delete = models.CASCADE,null=True, blank=True,default=None)
	decription =models.TextField(null=True ,blank=True)
	intro =models.TextField(null=True ,blank=True)
	module_length = models.CharField(max_length=100, null=True, blank=True,db_index=True)
	upload_date = models.DateTimeField(auto_now=True)

class ModuleItems(models.Model):
	module = models.ForeignKey(Module, related_name="module", verbose_name="Course", on_delete = models.CASCADE,null=True, blank=True,default=None)
	files = models.FileField(blank=True, null=True)
	notes = models.TextField(null=True ,blank=True)
	upload_date = models.DateTimeField(auto_now=True)

education/views.py
from django.shortcuts import render

# Create your views here.

web/templates/web/dashboards/education/course/add_course.html
{% extends 'web/dashboards/manager/base/base.html' %}
{% block content %}
		<!-- FORM VALIDATION -->
		<div class="row mt">
			<ul class="nav pull-right top-menu">
				<li><a class="logout" href="{% url 'users:view_executives' %}">View Executives</a></li>
			  </ul>
			<div class="col-lg-12">
			  <h4>Assign Role to Member</h4>
			  <div class="form-panel">
				<div class=" form">
					{% include 'web/dashboards/manager/base/_alerts.html' %}

				  <form class="cmxform form-horizontal style-form" id="commentForm" method="POST" action="{% url 'users:assign_member' %}">
					{% csrf_token %}
					<div class="form-group ">
						<label for="phone" class="control-label col-lg-2">Course Name (required)</label>
						<div class="col-lg-10">
						  <input class=" form-control" id="course_name" name="course_name" minlength="2" type="text" required />
						</div>
					  </div>
					<div class="form-group ">
						<label for="lead_tutor" class="control-label col-lg-2">Select Role(required)</label>
						<div class="col-lg-8">

							<select name="lead_tutor"  class="form-control">
								{% for lead_tutor in lead_tutors %}
								<option value="{{lead_tutor.id}}" >{{lead_tutor.id}}, {{lead_tutor.name }}</option>
								{% endfor %}
							  </select>	
						</div>
						<div class="col-lg-2">
							<a href="{% url 'users:add_tutor' %}">
								<i class="fa fa-plus"></i> add tutor
							</a>

						  </div>
					  </div>

					  <div class="form-group ">
						<label for="course_length" class="control-label col-lg-2">Course Length (required)</label>
						<div class="col-lg-10">
						  <input class=" form-control" id="course_length" name="course_length" minlength="2" type="text" required />
						</div>
					  </div>


					<div class="form-group">
					  <div class="col-lg-offset-2 col-lg-10">
						<button class="btn btn-theme" type="submit">Save</button>
						<button class="btn btn-theme04" type="button">Cancel</button>
					  </div>
					</div>
				  </form>
				</div>
			  </div>
			  <!-- /form-panel -->
			</div>
			<!-- /col-lg-12 -->
		  </div>
		  <!-- /row -->


		  {% endblock %}