mainapp/urls.py
from django.contrib import admin
from django.urls import path, include
# machine learning calls
# from prediction.urls import urlpatterns as endpoints_urlpatterns

# static files config
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import url


from web import views
urlpatterns = [
    # APIs
    path('login', views.Index.as_view(), name="index"),
    path('admin/', admin.site.urls),
    # path('api/auth/', include('users.urls')),
    # path('api/', include('prediction.urls')),


    # Templates
    path('', views.Index.as_view(), name='index'),
    path('users/', include('users.urls')),
    path('web/', include('web.urls')),
    path('sacco/', include('sacco.urls')),

    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    
]
# urlpatterns += endpoints_urlpatterns
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from users.views import *
from django.conf.urls import url
app_name = 'users'
urlpatterns = [
   path('index/', index, name='index'),
   path('logout/', logout, name='logout'),
   path('add_tutor/', add_tutor, name='add_tutor'),
   path('add_new_member/', add_new_member, name='add_new_member'),
   path('add_sacco/', add_sacco, name='add_sacco'),
   path('add_city/', add_city, name='add_city'),
   path('get_citites/', get_citites, name='get_citites'),
   path('get_countries/', get_countries, name='get_countries'),
   path('assign_member/', assign_member, name='assign_member'),
   path('view_members/', view_members, name='view_members'),
   path('view_tutors/', view_tutors, name='view_tutors'),
   path('assign_tutor/', assign_tutor, name='assign_tutor'),
   path('view_executives/', view_executives, name='view_executives'),
   path('sign_up/',sign_up,name='sign_up'),
   path('sign_in/', sign_in, name='sign_in'),
#    path('profile/$', profile, name='profile'),
    # path('login/', APILoginView.as_view(), name='api_login')
   url(
        r"^profile/(?P<profile_id>.)", profile, name="profile"
    ),
]

web/urls.py
from django.urls import path, include
from web import views
from django.conf.urls import url
app_name = 'web'

urlpatterns = [
	path('home', views.Index.as_view(), name="home"),
	path('apply', views.Apply.as_view(), name="apply"),
	path('alumni', views.Alumni.as_view(), name="alumni"),
	path('contacts', views.Contacts.as_view(), name="contacts"),
	path('help', views.Help.as_view(), name="help"),
	path('sign_in', views.SignIn.as_view(), name="sign_in"),
	path('sign_up', views.SignUp.as_view(), name="sign_up"),
	path('research', views.Research.as_view(), name="research"),
	path('communites', views.Communites.as_view(), name="communites"),
	path('events', views.Events.as_view(), name="events"),
	path('our_staff', views.FacultyStaff.as_view(), name="our_staff"),
	path('future_members', views.FutureStudents.as_view(), name="future_members"),
	path('current_members', views.CurrentStudents.as_view(), name="current_members"),
	path('courses', views.Courses.as_view(), name="courses"),
    path('comment_post/<int:pk>/', views.comment_post, name='comment_post'),
    path('research_detail/<int:pk>/', views.ResearchDetailView.as_view(), name='research_detail'),

]

web/templates/web/dashboards/manager/base/_alerts.html
{% if messages %}
    {% for message in messages %}
        <div id="message" class="container">
            <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
                <strong>
                    {% if message.level == DEFAUT_MESSAGE_LEVELS.ERROR %}
                        Error
                    {% else %}
                        {{ message.tags|title }}
                    {% endif %}
                </strong>
                {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}

web/templates/web/dashboards/manager/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="Dashboard">
  <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
  <title>SACCOSTALLION-APP</title>

  <!-- Favicons -->
  <link href="{% static 'dash_assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'dash_assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Bootstrap core CSS -->
  <link href="{% static 'dash_assets/lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <!--external css-->
  <link href="{% static 'dash_assets/lib/font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
  <link rel="stylesheet" type="text/css" href="{% static 'dash_assets/css/zabuto_calendar.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dash_assets/lib/gritter/css/jquery.gritter.css' %}" />
  <link href="{% static 'dash_assets/lib/advanced-datatable/css/demo_page.css' %}" rel="stylesheet" />
  <link href="{% static 'dash_assets/lib/advanced-datatable/css/demo_table.css' %}" rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'dash_assets/lib/advanced-datatable/css/DT_bootstrap.css' %}" />
 
  
  
  <!-- Custom styles for this template -->
  <link href="{% static 'dash_assets/css/style.css' %}" rel="stylesheet">
  <link href="{% static 'dash_assets/css/style-responsive.css' %}" rel="stylesheet">
  <script src="{% static 'dash_assets/lib/chart-master/Chart.js' %}"></script>

  <!-- =======================================================
    Template Name: Dashio
    Template URL: https://templatemag.com/dashio-bootstrap-admin-template/
    Author: TemplateMag.com
    License: https://templatemag.com/license/
  ======================================================= -->
</head>

<body>
  <section id="container">
{% include 'web/dashboards/manager/base/header.html' %}
{% include 'web/dashboards/manager/base/side_bar.html' %}

<section id="main-content">
    <section class="wrapper">
        {% block content %} {% endblock %}
        </section>
</section>
  </section>
  <script src="{% static 'dash_assets/lib/jquery/jquery.min.js' %}"></script>

  <script src="{% static 'dash_assets/lib/bootstrap/js/bootstrap.min.js' %}"></script>
  <script class="include" type="text/javascript" src="{% static 'dash_assets/lib/jquery.dcjqaccordion.2.7.js' %}"></script>
  <script src="{% static 'dash_assets/lib/jquery.scrollTo.min.js' %}"></script>
  <script src="{% static 'dash_assets/lib/jquery.nicescroll.js' %}" type="text/javascript"></script>
  <script src="{% static 'dash_assets/lib/jquery.sparkline.js' %}"></script>
  <!--common script for all pages-->
  <script src="{% static 'dash_assets/lib/common-scripts.js' %}"></script>
  <script type="text/javascript" src="{% static 'dash_assets/lib/gritter/js/jquery.gritter.js' %}"></script>
  <script type="text/javascript" src="{% static 'dash_assets/lib/gritter-conf.js' %}"></script>
  <!--script for this page-->
  <script src="{% static 'dash_assets/lib/sparkline-chart.js' %}"></script>
  <script src="{% static 'dash_assets/lib/zabuto_calendar.js' %}"></script>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyASm3CwaK9qtcZEWYa-iQwHaGi3gcosAJc&sensor=false"></script>
  
  <script src="{% static 'dash_assets/lib/form-validation-script.js' %}"></script>
 
 
  <script type="text/javascript" language="javascript" src="{% static 'dash_assets/lib/advanced-datatable/js/jquery.dataTables.js' %}"></script>
  <script type="text/javascript" src="{% static 'dash_assets/lib/advanced-datatable/js/DT_bootstrap.js' %}"></script>
  <!--common script for all pages-->

  <!-- <script src="{% static 'dash_assets/lib/common-scripts.js' %}"></script> -->
  
  <script type="text/javascript">
    /* Formating function for row details */
    function fnFormatDetails(oTable, nTr) {
      var aData = oTable.fnGetData(nTr);
      var sOut = '<table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;">';
      sOut += '<tr><td>Rendering engine:</td><td>' + aData[1] + ' ' + aData[4] + '</td></tr>';
      sOut += '<tr><td>Link to source:</td><td>Could provide a link here</td></tr>';
      sOut += '<tr><td>Extra info:</td><td>And any further details here (images etc)</td></tr>';
      sOut += '</table>';

      return sOut;
    }

    $(document).ready(function() {
      /*
       * Insert a 'details' column to the table
       */
       var nCloneTh = document.createElement('th');
      var nCloneTd = document.createElement('td');
      nCloneTd.innerHTML = `<img src="{% static 'dash_assets/lib/advanced-datatable/images/details_open.png' %}">`;
      nCloneTd.className = "center";

      $('#hidden-table-info thead tr').each(function() {
        this.insertBefore(nCloneTh, this.childNodes[0]);
      });

      $('#hidden-table-info tbody tr').each(function() {
        this.insertBefore(nCloneTd.cloneNode(true), this.childNodes[0]);
      });

      /*
       * Initialse DataTables, with no sorting on the 'details' column
       */
      var oTable = $('#hidden-table-info').dataTable({
        "aoColumnDefs": [{
          "bSortable": false,
          "aTargets": [0]
        }],
        "aaSorting": [
          [1, 'asc']
        ]
      });

      /* Add event listener for opening and closing details
       * Note that the indicator for showing which row is open is not controlled by DataTables,
       * rather it is done here
       */
      $('#hidden-table-info tbody td img').live('click', function() {
        var nTr = $(this).parents('tr')[0];
        if (oTable.fnIsOpen(nTr)) {
          /* This row is already open - close it */
          this.src = "{% static 'dash_assets/lib/advanced-datatable/media/images/details_open.png";
          oTable.fnClose(nTr);
        } else {
          /* Open this row */
          this.src = "{% static 'dash_assets/lib/advanced-datatable/images/details_close.png";
          oTable.fnOpen(nTr, fnFormatDetails(oTable, nTr), 'details');
        }
      });

      var unique_id = $.gritter.add({
        // (string | mandatory) the heading of the notification
        title: 'Welcome to Dashio!',
        // (string | mandatory) the text inside the notification
        text: 'Hover me to enable the Close Button. You can hide the left sidebar clicking on the button next to the logo.',
        // (string | optional) the image to display on the left
        image: 'img/ui-sam.jpg',
        // (bool | optional) if you want it to fade out on its own or just sit there
        sticky: false,
        // (int | optional) the time you want it to be alive for before fading out
        time: 8000,
        // (string | optional) the class name you want to apply to that specific message
        class_name: 'my-sticky-class'
      });

      return false;
    });
  </script>
  <script type="application/javascript">
    $(document).ready(function() {
      $("#date-popover").popover({
        html: true,
        trigger: "manual"
      });
      $("#date-popover").hide();
      $("#date-popover").click(function(e) {
        $(this).hide();
      });

      $("#my-calendar").zabuto_calendar({
        action: function() {
          return myDateFunction(this.id, false);
        },
        action_nav: function() {
          return myNavFunction(this.id);
        },
        ajax: {
          url: "show_data.php?action=1",
          modal: true
        },
        legend: [{
            type: "text",
            label: "Special event",
            badge: "00"
          },
          {
            type: "block",
            label: "Regular event",
          }
        ]
      });
    });

    function myNavFunction(id) {
      $("#date-popover").hide();
      var nav = $("#" + id).data("navigation");
      var to = $("#" + id).data("to");
      console.log('nav ' + nav + ' to: ' + to.month + '/' + to.year);
    }
  </script>

<script>
    $('.contact-map').click(function() {

      //google map in tab click initialize
      function initialize() {
        var myLatlng = new google.maps.LatLng(40.6700, -73.9400);
        var mapOptions = {
          zoom: 11,
          scrollwheel: false,
          center: myLatlng,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        var map = new google.maps.Map(document.getElementById('map'), mapOptions);
        var marker = new google.maps.Marker({
          position: myLatlng,
          map: map,
          title: 'Dashio Admin Theme!'
        });
      }
      google.maps.event.addDomListener(window, 'click', initialize);
    });
  </script>
</body>

</html>

web/templates/web/dashboards/manager/base/header.html
{% load static %}
	 
	 <!-- **********************************************************************************************************************************************************
				TOP BAR CONTENT & NOTIFICATIONS
				*********************************************************************************************************************************************************** -->
		<!--header start-->
		<header class="header black-bg">
				<div class="sidebar-toggle-box">
					<div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
				</div>
				<!--logo start-->
				<a href="{% url 'users:index' %}" class="logo"><b>SACCOSTALLION<span> APP</span></b></a>
				<!--logo end-->
				<div class="nav notify-row" id="top_menu">
					<!--  notification start -->
					<ul class="nav top-menu">
						<!-- settings start -->
						<li class="dropdown">
							<a data-toggle="dropdown" class="dropdown-toggle" href="{% url 'users:index' %}">
								<i class="fa fa-tasks"></i>
								<span class="badge bg-theme">4</span>
								</a>
							<ul class="dropdown-menu extended tasks-bar">
								<div class="notify-arrow notify-arrow-green"></div>
								<li>
									<p class="green">You have 4 pending tasks</p>
								</li>
								<li>
									<a href="{% url 'users:index' %}">
										<div class="task-info">
											<div class="desc">Dashio Admin Panel</div>
											<div class="percent">40%</div>
										</div>
										<div class="progress progress-striped">
											<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
												<span class="sr-only">40% Complete (success)</span>
											</div>
										</div>
									</a>
								</li>
								<li>
									<a href="{% url 'users:index' %}">
										<div class="task-info">
											<div class="desc">Database Update</div>
											<div class="percent">60%</div>
										</div>
										<div class="progress progress-striped">
											<div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
												<span class="sr-only">60% Complete (warning)</span>
											</div>
										</div>
									</a>
								</li>
								<li>
									<a href="{% url 'users:index' %}">
										<div class="task-info">
											<div class="desc">Product Development</div>
											<div class="percent">80%</div>
										</div>
										<div class="progress progress-striped">
											<div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
												<span class="sr-only">80% Complete</span>
											</div>
										</div>
									</a>
								</li>
								<li>
									<a href="{% url 'users:index' %}">
										<div class="task-info">
											<div class="desc">Payments Sent</div>
											<div class="percent">70%</div>
										</div>
										<div class="progress progress-striped">
											<div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width: 70%">
												<span class="sr-only">70% Complete (Important)</span>
											</div>
										</div>
									</a>
								</li>
								<li class="external">
									<a href="#">See All Tasks</a>
								</li>
							</ul>
						</li>
						<!-- settings end -->
						<!-- inbox dropdown start-->
						<li id="header_inbox_bar" class="dropdown">
							<a data-toggle="dropdown" class="dropdown-toggle" href="{% url 'users:index' %}">
								<i class="fa fa-envelope-o"></i>
								<span class="badge bg-theme">5</span>
								</a>
							<ul class="dropdown-menu extended inbox">
								<div class="notify-arrow notify-arrow-green"></div>
								<li>
									<p class="green">You have 5 new messages</p>
								</li>
								<li>
									<a href="{% url 'users:index' %}">
										<span class="photo"><img alt="avatar" src="img/ui-zac.jpg"></span>
										<span class="subject">
										<span class="from">Zac Snider</span>
										<span class="time">Just now</span>
										</span>
										<span class="message">
										Hi mate, how is everything?
										</span>
										</a>
								</li>
								<li>
									<a href="{% url 'users:index' %}">
										<span class="photo"><img alt="avatar" src="img/ui-divya.jpg"></span>
										<span class="subject">
										<span class="from">Divya Manian</span>
										<span class="time">40 mins.</span>
										</span>
										<span class="message">
										Hi, I need your help with this.
										</span>
										</a>
								</li>
								<li>
									<a href="{% url 'users:index' %}">
										<span class="photo"><img alt="avatar" src="img/ui-danro.jpg"></span>
										<span class="subject">
										<span class="from">Dan Rogers</span>
										<span class="time">2 hrs.</span>
										</span>
										<span class="message">
										Love your new Dashboard.
										</span>
										</a>
								</li>
								<li>
									<a href="{% url 'users:index' %}">
										<span class="photo"><img alt="avatar" src="img/ui-sherman.jpg"></span>
										<span class="subject">
										<span class="from">Dj Sherman</span>
										<span class="time">4 hrs.</span>
										</span>
										<span class="message">
										Please, answer asap.
										</span>
										</a>
								</li>
								<li>
									<a href="{% url 'users:index' %}">See all messages</a>
								</li>
							</ul>
						</li>
						<!-- inbox dropdown end -->
						<!-- notification dropdown start-->
						<li id="header_notification_bar" class="dropdown">
							<a data-toggle="dropdown" class="dropdown-toggle" href="{% url 'users:index' %}">
								<i class="fa fa-bell-o"></i>
								<span class="badge bg-warning">7</span>
								</a>
							<ul class="dropdown-menu extended notification">
								<div class="notify-arrow notify-arrow-yellow"></div>
								<li>
									<p class="yellow">You have 7 new notifications</p>
								</li>
								<li>
									<a href="{% url 'users:index' %}">
										<span class="label label-danger"><i class="fa fa-bolt"></i></span>
										Server Overloaded.
										<span class="small italic">4 mins.</span>
										</a>
								</li>
								<li>
									<a href="{% url 'users:index' %}">
										<span class="label label-warning"><i class="fa fa-bell"></i></span>
										Memory #2 Not Responding.
										<span class="small italic">30 mins.</span>
										</a>
								</li>
								<li>
									<a href="{% url 'users:index' %}">
										<span class="label label-danger"><i class="fa fa-bolt"></i></span>
										Disk Space Reached 85%.
										<span class="small italic">2 hrs.</span>
										</a>
								</li>
								<li>
									<a href="{% url 'users:index' %}">
										<span class="label label-success"><i class="fa fa-plus"></i></span>
										New User Registered.
										<span class="small italic">3 hrs.</span>
										</a>
								</li>
								<li>
									<a href="{% url 'users:index' %}">See all notifications</a>
								</li>
							</ul>
						</li>
						<!-- notification dropdown end -->
					</ul>
					<!--  notification end -->
				</div>
				<div class="top-menu">
					<ul class="nav pull-right top-menu">
						<li><a class="logout" href="{% url 'users:logout' %}">Logout</a></li>
					</ul>
				</div>
			</header>
			<!--header end-->

web/templates/web/dashboards/manager/base/side_bar.html
m    <!-- **********************************************************************************************************************************************************
				MAIN SIDEBAR MENU
				*********************************************************************************************************************************************************** -->
		<!--sidebar start-->
		<aside>
				<div id="sidebar" class="nav-collapse ">
					<!-- sidebar menu start-->
					<ul class="sidebar-menu" id="nav-accordion">
						{% if loged_in_user.profile_pic %}
						<p class="centered"><a href="{% url 'users:profile' user.id %}">
						
							<img src="{{ loged_in_user.profile_pic.url }}" class="img-circle" width="80">
					
						</p>
						{% endif %}
						<h5 class="centered">{{loged_in_user.id}} {{loged_in_user.user.first_name}} {{ user.organization}}</h5>
					</a>
					 <li class="mt">
							<a class="active" href="index.html">
								<i class="fa fa-dashboard"></i>
								<span>Dashboard</span>
								</a>
						</li>
						<li class="sub-menu">
							<a href="javascript:;">
								<i class="fa fa-desktop"></i>
								<span>Members</span>
								</a>
							<ul class="sub">
								<li><a href="{% url 'users:assign_member' %}">Executive</a></li>
								<li><a href="{% url 'users:view_tutors' %}">Tutors</a></li>
								<li><a href="{% url 'users:view_members' %}">New Member</a></li>
								<!-- <li><a href="font_awesome.html">Font Awesome</a></li> -->
							</ul>
						</li>
						<li class="sub-menu">
							<a href="javascript:;">
								<i class="fa fa-cogs"></i>
								<span>Subscriptions</span>
								</a>
							<ul class="sub">
								<li><a href="grids.html">Executive</a></li>
								<li><a href="calendar.html">Ordinary</a></li>
								<li><a href="gallery.html">Loans</a></li>
							</ul>
						</li>
						<li class="sub-menu">
							<a href="javascript:;">
								<i class="fa fa-book"></i>
								<span>Education Content</span>
								</a>
							<ul class="sub">
								<li><a href="blank.html">Business</a></li>
								<li><a href="login.html">Individual</a></li>
								<li><a href="lock_screen.html">users</a></li>
								<li><a href="profile.html">Trainers</a></li>
							</ul>
						</li>
						<li class="sub-menu">
							<a href="javascript:;">
								<i class="fa fa-tasks"></i>
								<span>Accounting</span>
								</a>
							<ul class="sub">
								<li><a href="form_component.html">Recievables</a></li>
								<li><a href="advanced_form_components.html">Payables</a></li>
								<li><a href="form_validation.html">Reports</a></li>

							</ul>
						</li>
					</ul>
					<!-- sidebar menu end-->
				</div>
			</aside>
			<!--sidebar end-->