mainapp/urls.py
from django.contrib import admin
from django.urls import path, include
# machine learning calls
# from prediction.urls import urlpatterns as endpoints_urlpatterns

# static files config
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import url


from web import views
urlpatterns = [
    # APIs
    path('login', views.Index.as_view(), name="index"),
    path('admin/', admin.site.urls),
    # path('api/auth/', include('users.urls')),
    # path('api/', include('prediction.urls')),


    # Templates
    path('', views.Index.as_view(), name='index'),
    path('users/', include('users.urls')),
    path('web/', include('web.urls')),
    path('sacco/', include('sacco.urls')),

    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    
]
# urlpatterns += endpoints_urlpatterns
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from users.views import *
from django.conf.urls import url
app_name = 'users'
urlpatterns = [
   path('index/', index, name='index'),
   path('logout/', logout, name='logout'),
   path('add_tutor/', add_tutor, name='add_tutor'),
   path('add_new_member/', add_new_member, name='add_new_member'),
   path('add_sacco/', add_sacco, name='add_sacco'),
   path('add_city/', add_city, name='add_city'),
   path('get_citites/', get_citites, name='get_citites'),
   path('get_countries/', get_countries, name='get_countries'),
   path('assign_member/', assign_member, name='assign_member'),
   path('view_members/', view_members, name='view_members'),
   path('view_tutors/', view_tutors, name='view_tutors'),
   path('assign_tutor/', assign_tutor, name='assign_tutor'),
   path('view_executives/', view_executives, name='view_executives'),
   path('sign_up/',sign_up,name='sign_up'),
   path('sign_in/', sign_in, name='sign_in'),
#    path('profile/$', profile, name='profile'),
    # path('login/', APILoginView.as_view(), name='api_login')
   url(
        r"^profile/(?P<profile_id>.)", profile, name="profile"
    ),
]

web/urls.py
from django.urls import path, include
from web import views
from django.conf.urls import url
app_name = 'web'

urlpatterns = [
	path('home', views.Index.as_view(), name="home"),
	path('apply', views.Apply.as_view(), name="apply"),
	path('alumni', views.Alumni.as_view(), name="alumni"),
	path('contacts', views.Contacts.as_view(), name="contacts"),
	path('help', views.Help.as_view(), name="help"),
	path('sign_in', views.SignIn.as_view(), name="sign_in"),
	path('sign_up', views.SignUp.as_view(), name="sign_up"),
	path('research', views.Research.as_view(), name="research"),
	path('communites', views.Communites.as_view(), name="communites"),
	path('events', views.Events.as_view(), name="events"),
	path('our_staff', views.FacultyStaff.as_view(), name="our_staff"),
	path('future_members', views.FutureStudents.as_view(), name="future_members"),
	path('current_members', views.CurrentStudents.as_view(), name="current_members"),
	path('courses', views.Courses.as_view(), name="courses"),
    path('comment_post/<int:pk>/', views.comment_post, name='comment_post'),
    path('research_detail/<int:pk>/', views.ResearchDetailView.as_view(), name='research_detail'),

]

web/templates/web/dashboards/manager/members/add_member.html
{% extends 'web/dashboards/manager/base/base.html' %}
{% block content %}
		<!-- FORM VALIDATION -->
		<div class="row mt">
			<ul class="nav pull-right top-menu">
				<li><a class="logout" href="{% url 'users:view_members' %}">View Members</a></li>
			  </ul>
			<div class="col-lg-12">

			  <h4>Add Member</h4>
			  <div class="form-panel">
				<div class=" form">
					{% include 'web/dashboards/manager/base/_alerts.html' %}

				  <form class="cmxform form-horizontal style-form" id="commentForm" method="POST" action="{% url 'users:add_new_member' %}">
					{% csrf_token %}
					
					<div class="form-group ">
						<label for="phone" class="control-label col-lg-2">Whatsapp Number (required)</label>
						<div class="col-lg-10">
						  <input class=" form-control" id="whatsapp_number" name="whatsapp_number" minlength="2" type="text" required />
						</div>
					  </div>
					  <div class="form-group ">
						<label for="phone" class="control-label col-lg-2">Direct Calls Number (required)</label>
						<div class="col-lg-10">
						  <input class=" form-control" id="direct_number" name="direct_number" minlength="2" type="text" required />
						</div>
					  </div>
					<div class="form-group ">
						<label for="cname" class="control-label col-lg-2">First Name (required)</label>
						<div class="col-lg-10">
						  <input class=" form-control" id="first_name" name="first_name" minlength="2" type="text" required />
						</div>
					  </div>					
					  <div class="form-group ">
						<label for="cname" class="control-label col-lg-2">Last Name (required)</label>
						<div class="col-lg-10">
						  <input class=" form-control" id="last_name" name="last_name" minlength="2" type="text" required />
						</div>
					  </div>
					  <div class="form-group ">
						<label for="cname" class="control-label col-lg-2">National ID (required)</label>
						<div class="col-lg-10">
						  <input class=" form-control" id="national_id" name="national_id" minlength="2" type="text" required />
						</div>
					  </div>
					<div class="form-group ">
					  <label for="cemail" class="control-label col-lg-2">E-Mail (required)</label>
					  <div class="col-lg-10">
						<input class="form-control " id="cemail" type="email" name="email" required />
					  </div>
					</div>
					<div class="form-group ">
					  <label for="curl" class="control-label col-lg-2">Facebook Account link (optional)</label>
					  <div class="col-lg-10">
						<input class="form-control " id="curl" type="url" name="url" />
					  </div>
					</div>
					<div class="form-group ">
					  <label for="home_address" class="control-label col-lg-2">Home Address (required)</label>
					  <div class="col-lg-10">
						<textarea class="form-control " id="home_address" name="home_address" required></textarea>
					  </div>
					</div>

					<div class="form-group ">
						<label for="select_city"  class="control-label col-lg-2">Select City (required)</label>

						<div class="col-lg-10">
							<select name="city" class="form-control">
								<option>Harare</option>
								<option>Gweru</option>
								<option>Bulawayo</option>
								<option>Gwanda</option>
								<option>Norton</option>
							  </select>
						</div>
					  </div>
					
					<div class="form-group">
					  <div class="col-lg-offset-2 col-lg-10">
						<button class="btn btn-theme" type="submit">Save</button>
						<button class="btn btn-theme04" type="button">Cancel</button>
					  </div>
					</div>
				  </form>
				</div>
			  </div>
			  <!-- /form-panel -->
			</div>
			<!-- /col-lg-12 -->
		  </div>
		  <!-- /row -->
		  {% endblock %}

web/templates/web/dashboards/manager/members/assign_member.html
{% extends 'web/dashboards/manager/base/base.html' %}
{% block content %}
		<!-- FORM VALIDATION -->
		<div class="row mt">
			<ul class="nav pull-right top-menu">
				<li><a class="logout" href="{% url 'users:view_executives' %}">View Executives</a></li>
			  </ul>
			<div class="col-lg-12">
			  <h4>Assign Role to Member</h4>
			  <div class="form-panel">
				<div class=" form">
					{% include 'web/dashboards/manager/base/_alerts.html' %}

				  <form class="cmxform form-horizontal style-form" id="commentForm" method="POST" action="{% url 'users:assign_member' %}">
					{% csrf_token %}

					<div class="form-group ">
						<label for="city" class="control-label col-lg-2">Select Role(required)</label>
						<div class="col-lg-8">

							<select name="role"  class="form-control">
								{% for role in roles %}
								<option value="{{role.id}}" >{{role.id}}, {{role.name }}</option>
								{% endfor %}
							  </select>	
						</div>
						<div class="col-lg-2">
							<a href="{% url 'users:view_tutors' %}">
								<i class="fa fa-plus"></i> add role
							</a>

						  </div>
					  </div>

					  <div class="form-group ">
						<label for="city" class="control-label col-lg-2">Select Member(required)</label>
						<div class="col-lg-8">

							<select name="member"  class="form-control">
								{% for member in members %}
								<option value="{{member.id}}" >{{member.id}}, {{  member.user.first_name }}</option>
								{% endfor %}
							  </select>	
						</div>
						<div class="col-lg-2">
							<a href="{% url 'users:view_tutors' %}">
								<i class="fa fa-plus"></i> add member
							</a>

						  </div>
					  </div>


					<div class="form-group">
					  <div class="col-lg-offset-2 col-lg-10">
						<button class="btn btn-theme" type="submit">Save</button>
						<button class="btn btn-theme04" type="button">Cancel</button>
					  </div>
					</div>
				  </form>
				</div>
			  </div>
			  <!-- /form-panel -->
			</div>
			<!-- /col-lg-12 -->
		  </div>
		  <!-- /row -->


		  {% endblock %}

web/templates/web/dashboards/manager/members/assign_tutor.html
{% extends 'web/dashboards/manager/base/base.html' %}
{% block content %}
		<!-- FORM VALIDATION -->

		<div class="row mt">
			<ul class="nav pull-right top-menu">
				<li><a class="logout" href="{% url 'users:view_tutors' %}">View Tutors</a></li>
			  </ul>
			<div class="col-lg-12">
			  <h4>Assign Tutor</h4>
			  <div class="form-panel">
				<div class=" form">
					{% include 'web/dashboards/manager/base/_alerts.html' %}

				  <form class="cmxform form-horizontal style-form" id="commentForm" method="POST" action="{% url 'users:assign_member' %}">
					{% csrf_token %}

					<div class="form-group ">
						<label for="city" class="control-label col-lg-2">Select Course(required)</label>
						<div class="col-lg-8">

							<select name="course"  class="form-control">
								{% for course in courses %}
								<option value="{{course.id}}" >{{course.id}}, {{course.name }}</option>
								{% endfor %}
								
							  </select>	
			

							  <!-- <ul class="nav pull-right top-menu">
								<li></li>
							  </ul> -->
						</div>
						<div class="col-lg-2">
							<a href="{% url 'users:view_tutors' %}">
								<i class="fa fa-plus"></i> add course
							</a>

						  </div>
					  </div>

					  <div class="form-group ">
						<label for="city" class="control-label col-lg-2">Select Tutor(required)</label>
						<div class="col-lg-8">

							<select name="tutor"  class="form-control">
								{% for tutor in tutors %}
								<option value="{{tutor.id}}" >{{tutor.id}}, {{  tutor.user.first_name }}</option>
								{% endfor %}
							  </select>

						</div>
						<div class="col-lg-2">
							<a href="{% url 'users:view_tutors' %}">
								<i class="fa fa-plus"></i> add tutor
							</a>

						  </div>
					  </div>


					<div class="form-group">
					  <div class="col-lg-offset-2 col-lg-10">
						<button class="btn btn-theme" type="submit">Save</button>
						<button class="btn btn-theme04" type="button">Cancel</button>
					  </div>
					</div>
				  </form>
				</div>
			  </div>
			  <!-- /form-panel -->
			</div>
			<!-- /col-lg-12 -->
		  </div>
		  <!-- /row -->


		  {% endblock %}

web/templates/web/dashboards/manager/members/view_executives.html
{% extends 'web/dashboards/manager/base/base.html' %}
{% block content %}
<ul class="nav pull-right top-menu">
	<li><a class="logout" href="{% url 'users:assign_tutor' %}">Add New Executive Member</a></li>
  </ul>
	<h3>Tutors </h3>


	<div style="margin:1%;" class="row mb">
	  <!-- page start-->
	  <div class="content-panel">
		<div style="margin:1%;" class="adv-table">
		  <table cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" id="hidden-table-info">
			<thead>
			  <tr>
				<th>id</th>
				<th>First Name</th>
				<th class="hidden-phone">Last Name</th>
				<th class="hidden-phone">Membership Role</th>
				<th class="hidden-phone">phone</th>
			  </tr>
			</thead>
			<tbody>
{% for member in members %}
			  <tr class="gradeU">
				<td>{{member.id}}</td>
				<td>{{member.user.first_name}}</td>
				<td class="hidden-phone">{{member.user.last_name}}</td>
				<td class="center hidden-phone">{{member.membership_role}}</td>
				<td class="center hidden-phone">{{member.whatsapp_number}}</td>
			  </tr>
	{% endfor %}
			</tbody>
		  </table>
		</div>
	  </div>
	  <!-- page end-->
	</div>
	<!-- /row -->
  </section>
  <!-- /wrapper -->
  {% endblock %}

web/templates/web/dashboards/manager/members/view_members.html
{% extends 'web/dashboards/manager/base/base.html' %}
{% block content %}
<ul class="nav pull-right top-menu">
	<li><a class="logout" href="{% url 'users:add_new_member' %}">Add New Member</a></li>
  </ul>
	<h3>Members </h3>


	<div style="margin:1%;" class="row mb">
	  <!-- page start-->
	  <div class="content-panel">
		<div style="margin:1%;" class="adv-table">
		  <table cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" id="hidden-table-info">
			<thead>
			  <tr>
				<th>id</th>
				<th>First Name</th>
				<th class="hidden-phone">Last Name</th>
				<th class="hidden-phone">Membership Role</th>
				<th class="hidden-phone">phone</th>
			  </tr>
			</thead>
			<tbody>
{% for member in members %}
			  <tr class="gradeU">
				<td>{{member.id}}</td>
				<td>{{member.user.first_name}}</td>
				<td class="hidden-phone">{{member.user.last_name}}</td>
				<td class="center hidden-phone">{{member.membership_role}}</td>
				<td class="center hidden-phone">{{member.whatsapp_number}}</td>
			  </tr>
	{% endfor %}
			</tbody>
		  </table>
		</div>
	  </div>
	  <!-- page end-->
	</div>
	<!-- /row -->
  </section>
  <!-- /wrapper -->
  {% endblock %}

web/templates/web/dashboards/manager/members/view_tutors.html
{% extends 'web/dashboards/manager/base/base.html' %}
{% block content %}
<ul class="nav pull-right top-menu">
	<li><a class="logout" href="{% url 'users:assign_tutor' %}">Add New Tutor</a></li>
  </ul>
	<h3>Tutors </h3>


	<div style="margin:1%;" class="row mb">
	  <!-- page start-->
	  <div class="content-panel">
		<div style="margin:1%;" class="adv-table">
		  <table cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" id="hidden-table-info">
			<thead>
			  <tr>
				<th>id</th>
				<th>First Name</th>
				<th class="hidden-phone">Last Name</th>
				<th class="hidden-phone">Membership Role</th>
				<th class="hidden-phone">phone</th>
			  </tr>
			</thead>
			<tbody>
{% for member in members %}
			  <tr class="gradeU">
				<td>{{member.id}}</td>
				<td>{{member.user.first_name}}</td>
				<td class="hidden-phone">{{member.user.last_name}}</td>
				<td class="center hidden-phone">{{member.membership_role}}</td>
				<td class="center hidden-phone">{{member.whatsapp_number}}</td>
			  </tr>
	{% endfor %}
			</tbody>
		  </table>
		</div>
	  </div>
	  <!-- page end-->
	</div>
	<!-- /row -->
  </section>
  <!-- /wrapper -->
  {% endblock %}